# Generated by Django 4.2.5 on 2025-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.IntegerField()),
                ('fullname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('status', models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='service_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.IntegerField()),
                ('fullname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('speed', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='super_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
